export type Role = 'buyer' | 'seller';
export type Tier = { min: number; price: number };
export type Product = {
  id: string; name: string; category: string; seller: string; sellerCity: string;
  min: number; max: number; stock: number; tiers: Tier[]; shipping: number; dispatch: string;
  delivery: string; quality: string; specs: string[]; returns: string; art: string; tint: string;
};
export type PoolStatus = 'open' | 'locked' | 'early' | 'capacity' | 'failed';
export type Pool = {
  id: string; name: string; spec: string; category: string; price: number; originalPrice: number;
  minimum: number; revisedMinimum?: number; max: number; paid: number; interested: number;
  status: PoolStatus; day: number; closesIn: string; dispatch: string; seller: string; sellerCity: string;
  commitment: string; sellerOffer?: { min: number; price: number; days: number; extension: boolean; acceptedByBuyer?: boolean };
  offerPaid?: number; offerLocked?: boolean; extensionEndDay?: number;
  art: string; tint: string; note?: string; refundTotal?: number;
};
export type Quote = { id: string; supplier: string; city: string; unitPrice: number; shipping: number; lead: string; delivery: string; fit: string; quality: string; reliability: string; capacity: number; validity: string; status?: 'awarded' | 'expired' };
export type RFQ = { id: string; title: string; category: string; qty: number; material: string; dimensions: string; logo: string; colours: string; budget: string; city: string; needed: string; quality: string; status: 'draft' | 'published' | 'quoted' | 'awarded' | 'paid' | 'fulfilment' | 'completed'; quotes: Quote[]; buyer: string; awardedQuoteId?: string; createdAt: string };
export type Order = { id: string; kind: 'direct' | 'pool' | 'rfq'; title: string; qty: number; unitPrice: number; shipping: number; total: number; seller: string; buyer: string; status: string; createdAt: string; poolId?: string; rfqId?: string; quoteId?: string; issueAllowed?: boolean };
export type Claim = { id: string; orderId: string; title: string; reason: string; qty: number; details: string; status: 'Submitted' | 'Seller reviewing' | 'Replacement agreed' | 'Refund approved' | 'Closed'; response?: string };
export type Notice = { id: string; title: string; body: string; type: 'pool' | 'rfq' | 'order' | 'claim'; read?: boolean };
export type DemoData = { loggedIn: boolean; role: Role | null; products: Product[]; pools: Pool[]; rfqs: RFQ[]; orders: Order[]; claims: Claim[]; notices: Notice[]; activePoolId: string; simDay: number; optionalRevenue: number; buyerInterest: Record<string, number>; poolDecisions: Record<string, 'buy'|'extend'|'cancel'>; };

export const seedProducts: Product[] = [
  { id:'p-tote', name:'Reusable cotton tote bags', category:'Bags & Packaging', seller:'Sundar Textiles', sellerCity:'Surat', min:50, max:1000, stock:1000, tiers:[{min:50,price:82},{min:200,price:72},{min:500,price:64}], shipping:250, dispatch:'Dispatch in 3–5 days', delivery:'Delivers to Chennai, Bengaluru and most major cities', quality:'220 GSM cotton canvas · double-stitched handles · pre-shrunk', specs:['Natural cotton canvas','38 × 42 cm, gusseted base','Screen print area: 25 × 28 cm','Sample available before production'], returns:'Bulk change-of-mind returns are unavailable. Wrong, damaged, missing or materially nonconforming units may be claimed within 5 days of delivery; affected units can be replaced or refunded.', art:'shopping-bag', tint:'sand' },
  { id:'p-school', name:'A4 ruled school notebooks', category:'School supplies', seller:'PaperNest Traders', sellerCity:'Chennai', min:100, max:2000, stock:1400, tiers:[{min:100,price:34},{min:500,price:29},{min:1000,price:25}], shipping:180, dispatch:'Dispatch in 2–4 days', delivery:'Delivers across Tamil Nadu and Karnataka', quality:'70 GSM paper · 172 pages · stitched binding', specs:['A4 size, 21 × 29.7 cm','Single-line ruling','Soft laminated cover','Carton of 40 units'], returns:'Wrong, damaged, missing or materially nonconforming units may be claimed within 5 days of delivery. No general change-of-mind returns for bulk cartons.', art:'book-open', tint:'blue' },
  { id:'p-shirt', name:'Everyday cotton crew-neck tee', category:'Apparel', seller:'Aruna Wholesale', sellerCity:'Tiruppur', min:60, max:800, stock:520, tiers:[{min:60,price:118},{min:200,price:102},{min:500,price:88}], shipping:300, dispatch:'Dispatch in 5–7 days', delivery:'Delivers to most serviceable pin codes', quality:'180 GSM combed cotton · colour-fast dye', specs:['Sizes S–XXL in mixed ratio','Black, white, navy and maroon','Pre-shrunk single jersey knit','Size chart shared before dispatch'], returns:'Wrong, damaged, missing or materially nonconforming units may be claimed within 5 days of delivery.', art:'shirt', tint:'rose' },
  { id:'p-steel', name:'Insulated steel water bottle', category:'Home & Kitchen', seller:'Metro Supply House', sellerCity:'Coimbatore', min:48, max:600, stock:420, tiers:[{min:48,price:189},{min:200,price:164},{min:400,price:149}], shipping:220, dispatch:'Dispatch in 4–6 days', delivery:'Delivers to Chennai and 200+ nearby cities', quality:'Double-wall 304-grade stainless steel', specs:['750 ml capacity','Leak-tested screw cap','Matte powder-coated finish','Food-contact test report available'], returns:'Wrong, damaged, missing or materially nonconforming units may be claimed within 5 days of delivery.', art:'bottle', tint:'mint' }
];

export function seedData(): DemoData {
  return {
    loggedIn:false, role:null, products:structuredClone(seedProducts),
    pools:[
      {id:'pool-open',name:'Canvas school tote · natural cotton',spec:'220 GSM canvas · 38 × 42 cm · no print',category:'Bags & Packaging',price:150,originalPrice:200,minimum:200,max:500,paid:140,interested:320,status:'open',day:4,closesIn:'Closes in 3 days',dispatch:'Dispatch 3 days after lock · delivery in 8–10 days',seller:'Sundar Textiles',sellerCity:'Surat',commitment:'Seller will fulfil paid units at ₹150 each once a 200-unit paid batch locks.',art:'shopping-bag',tint:'sand',note:'Four shop owners are comparing needs: 20 + 30 + 50 + 100 units. Free interest does not count toward the 200-unit minimum.'},
      {id:'pool-under',name:'Printed cotton drawstring bags',spec:'200 GSM cotton · single-colour print · 30 × 38 cm',category:'Bags & Packaging',price:148,originalPrice:148,minimum:200,max:400,paid:187,interested:310,status:'open',day:6,closesIn:'Decision due tomorrow · Day 7',dispatch:'Dispatch 4 days after confirmed batch',seller:'Sundar Textiles',sellerCity:'Surat',commitment:'187 units paid. The original 200-unit minimum is still unmet until the seller records a viable revised minimum.',art:'shopping-bag',tint:'rose',note:'Underfilled decision example: seller may accept 187 units at the same price, propose another viable price, offer a one-week extension, or cancel.'},
      {id:'pool-extension',name:'Colour-block cotton lunch bags',spec:'Cotton canvas · insulated lining · 24 × 18 cm',category:'Bags & Packaging',price:165,originalPrice:165,minimum:200,max:500,paid:187,interested:286,status:'open',day:6,closesIn:'Decision due tomorrow · Day 7',dispatch:'Dispatch 5 days after confirmed batch',seller:'Metro Supply House',sellerCity:'Coimbatore',commitment:'The seller offers a one-week extension. Each interested buyer must agree; silence adds no commitment.',sellerOffer:{min:200,price:165,days:7,extension:true},art:'shopping-bag',tint:'mint',note:'Extension is offered by the seller and must be accepted by each buyer. No automatic extension.'},
      {id:'pool-reprice',name:'Printed cotton drawstring bags · seller offer',spec:'200 GSM cotton · single-colour print · 30 × 38 cm',category:'Bags & Packaging',price:148,originalPrice:148,minimum:200,max:400,paid:187,interested:295,status:'open',day:6,closesIn:'Price offer valid today · Day 7',dispatch:'Dispatch 4 days after each confirmed cohort',seller:'Sundar Textiles',sellerCity:'Surat',commitment:'The original cohort needs 200 paid units. A separate revised-price offer is valid for 180 paid units; seller commits to fulfil that cohort at its accepted terms.',sellerOffer:{min:180,price:160,days:1,extension:false},art:'shopping-bag',tint:'rose',note:'Day N−1 alternative: the revised 180-unit cohort must reach its own paid minimum. It does not combine with 187 units paid at the original price.'},
      {id:'pool-success',name:'A4 ruled school notebooks · 172 pages',spec:'70 GSM · stitched binding · 40 per carton',category:'School supplies',price:150,originalPrice:200,minimum:200,max:500,paid:200,interested:320,status:'locked',day:5,closesIn:'Batch confirmed early',dispatch:'Dispatch in 3 days · delivery by 12 Oct',seller:'PaperNest Traders',sellerCity:'Chennai',commitment:'200 paid units confirmed at ₹150 each. Seller terms are locked for this batch.',art:'book-open',tint:'blue',note:'Four buyers wanted 20 + 30 + 50 + 100 = 200 units. The 20-unit buyer paid ₹3,000; the comparable individual price is ₹4,000, a ₹1,000 (25%) saving before unaccounted fees.'},
      {id:'pool-early',name:'Reusable cotton produce bags · 3 pack',spec:'Unbleached cotton mesh · assorted sizes',category:'Home & Kitchen',price:120,originalPrice:160,minimum:200,max:500,paid:240,interested:360,status:'early',day:3,closesIn:'Locked early · extra orders open',dispatch:'First 200-unit batch dispatches in 3 days; later units ship on 18 Oct',seller:'Metro Supply House',sellerCity:'Coimbatore',commitment:'First confirmed batch is protected. Seller committed to the displayed terms for remaining capacity.',art:'shopping-bag',tint:'mint'},
      {id:'pool-capacity',name:'Assorted school stationery kit',spec:'12-piece set · packed and labelled',category:'School supplies',price:98,originalPrice:140,minimum:200,max:500,paid:500,interested:620,status:'capacity',day:7,closesIn:'Maximum capacity reached',dispatch:'Dispatch in 4 days',seller:'PaperNest Traders',sellerCity:'Chennai',commitment:'Capacity reached. New buyers can join a no-payment waitlist.',art:'book-open',tint:'blue'},
      {id:'pool-failed',name:'Cotton apron bundle',spec:'240 GSM cotton · adjustable ties · 2 pack',category:'Apparel',price:175,originalPrice:220,minimum:200,max:400,paid:0,interested:240,status:'failed',day:7,closesIn:'Closed · paid orders refunded',dispatch:'Pool did not reach its paid minimum',seller:'Aruna Wholesale',sellerCity:'Tiruppur',commitment:'Only paid units count. The pool ended below its minimum; ₹24,500 in paid orders was refunded in this demo.',refundTotal:24500,art:'shirt',tint:'rose'}
    ],
    rfqs:[{
      id:'rfq-school',title:'Custom school gift bags',category:'Bags & Packaging',qty:500,material:'Recycled cotton canvas, 240 GSM',dimensions:'30 × 35 × 8 cm',logo:'One-colour school logo, front centre',colours:'Royal blue body, white handles',budget:'₹95–₹145 per delivered unit',city:'Chennai, Tamil Nadu',needed:'Deliver by 20 Oct 2026',quality:'Pre-production sample for approval; colour fastness and reinforced seams required',status:'quoted',buyer:'Bhupesh Stores',createdAt:'Today',quotes:[
        {id:'q1',supplier:'Sundar Textiles',city:'Surat',unitPrice:124,shipping:0,lead:'12 days',delivery:'18 Oct',fit:'Exact fabric, size and print match',quality:'Sample included · colour test report',reliability:'4.8/5 · 96% on-time',capacity:800,validity:'Valid 5 days'},
        {id:'q2',supplier:'Aruna Wholesale',city:'Tiruppur',unitPrice:108,shipping:3500,lead:'18 days',delivery:'24 Oct',fit:'Logo print included; 220 GSM fabric',quality:'Sample ₹400, credited on order',reliability:'4.5/5 · 89% on-time',capacity:600,validity:'Valid 3 days'},
        {id:'q3',supplier:'Metro Supply House',city:'Coimbatore',unitPrice:138,shipping:0,lead:'9 days',delivery:'15 Oct',fit:'Exact spec, premium recycled canvas',quality:'Pre-production sample included',reliability:'4.9/5 · 98% on-time',capacity:500,validity:'Valid 7 days'}
      ]
    }],
    orders:[
      {id:'MW-2201',kind:'direct',title:'Reusable cotton tote bags',qty:100,unitPrice:82,shipping:250,total:8450,seller:'Sundar Textiles',buyer:'Bhupesh Stores',status:'Confirmed · awaiting dispatch',createdAt:'Today',issueAllowed:true},
      {id:'MW-2202',kind:'pool',title:'Canvas school tote · natural cotton',qty:30,unitPrice:150,shipping:0,total:4500,seller:'Sundar Textiles',buyer:'North Star Stationery',status:'Paid · pool open',createdAt:'Yesterday',poolId:'pool-open'},
      {id:'MW-2203',kind:'pool',title:'Printed cotton drawstring bags',qty:187,unitPrice:148,shipping:0,total:27676,seller:'Sundar Textiles',buyer:'Pool buyers (5 shops)',status:'Paid · underfilled decision',createdAt:'Yesterday',poolId:'pool-under'},
      {id:'MW-2204',kind:'rfq',title:'Custom school gift bags',qty:500,unitPrice:124,shipping:0,total:62000,seller:'Sundar Textiles',buyer:'Bhupesh Stores',status:'Awarded · awaiting payment',createdAt:'Today',rfqId:'rfq-school',quoteId:'q1'},
      {id:'MW-2205',kind:'pool',title:'Colour-block cotton lunch bags',qty:187,unitPrice:165,shipping:0,total:30855,seller:'Metro Supply House',buyer:'Pool buyers (5 shops)',status:'Paid · extension offered',createdAt:'Yesterday',poolId:'pool-extension'},
      {id:'MW-2206',kind:'pool',title:'A4 ruled school notebooks · 172 pages',qty:20,unitPrice:150,shipping:0,total:3000,seller:'PaperNest Traders',buyer:'Bhupesh Stores',status:'Paid · batch confirmed',createdAt:'Today',poolId:'pool-success'},
      {id:'MW-2207',kind:'pool',title:'Printed cotton drawstring bags',qty:187,unitPrice:148,shipping:0,total:27676,seller:'Sundar Textiles',buyer:'Pool buyers (5 shops)',status:'Paid · underfilled decision',createdAt:'Yesterday',poolId:'pool-reprice'}
    ],
    claims:[{id:'CL-041',orderId:'MW-2201',title:'10 tote bags have weak seams',reason:'Quality differs from listing',qty:10,details:'Seams opened during a sample inspection. Placeholder photo attached.',status:'Seller reviewing'}],
    notices:[
      {id:'n1',title:'A pool decision is due tomorrow',body:'Printed cotton drawstring bags: 187 of 200 units are paid. Review the seller’s offer before Day 7.',type:'pool'},
      {id:'n2',title:'3 supplier quotes are ready',body:'Compare delivered price, sample terms and delivery dates for your 500 custom school gift bags.',type:'rfq'},
      {id:'n3',title:'Order MW-2201 is confirmed',body:'Sundar Textiles is preparing your 100-unit tote bag order.',type:'order'}
    ], activePoolId:'pool-open', simDay:4, optionalRevenue:0, buyerInterest:{'pool-open':20,'pool-extension':20,'pool-reprice':20}, poolDecisions:{}
  };
}

export const money = (n: number) => '₹' + Math.round(n).toLocaleString('en-IN');
export const unitPriceAt = (p: Product, qty: number) => [...p.tiers].sort((a,b)=>a.min-b.min).filter(t=>qty>=t.min).at(-1)?.price ?? p.tiers[0].price;
